# Generated by Django 6.0.3 on 2026-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
