# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_user_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
    ]
